Repository NoeMelo/HimnarioMMM, pull requests merged in 2022-01, with the labels that each got.

#6 Develop
  Coros/1.json
  Himnos/217.json
  Himnos/300.json
  imagenes/coros/1.jpg
  imagenes/himnos/217.jpg
  imagenes/himnos/300.jpg
Labels: enhancement

#8 Develop
  README.md
Labels: enhancement

#9 Test pull request - Anthem 7 (Jhordan sax)
  Himnos/7.json
  imagenes/himnos/7.jpg
Labels: Configuración

#12 Develop to Master
  Himnos/7.json
  imagenes/himnos/7.jpg
Labels: Configuración

#17 PR Semana 1
  Himnos/299.json
  imagenes/himnos/299.jpg
Labels: Himno

#19 Develop to Master [SEMANA 1]
  Himnos/10.json
  Himnos/11.json
  Himnos/13.json
  Himnos/14.json
  Himnos/15.json
  Himnos/17.json
  Himnos/18.json
  Himnos/19.json
  Himnos/299.json
  Himnos/7.json
  Himnos/8.json
  Himnos/9.json
  imagenes/himnos/10.jpg
  imagenes/himnos/11.jpg
  imagenes/himnos/13.jpg
  imagenes/himnos/14.jpg
  imagenes/himnos/15.jpg
  imagenes/himnos/17.jpg
  imagenes/himnos/18.jpg
  imagenes/himnos/19.jpg
  imagenes/himnos/299.jpg
  imagenes/himnos/8.jpg
  imagenes/himnos/9.jpg
Labels: Himno
